### PR TITLE
Filter out keywords with low occurrence count

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
Reasoning behind this - there's a lot of keywords that are listed only 1-2 times in the whole PyPI ecosystem - let's filter them out.

Command used:
```
f8a_tagger_cli.py -vvvv aggregate -i fabric8-analytics-tags/raw/pypi_tags.yaml -f yaml -o fabric8-analytics-tags/pypi_tags.yaml
```

**Review by sara-02 — COMMENTED** [review]
ML is also a synonym for machine learning

**Comment by fridex** [comment]
> ML is also a synonym for machine learning

It's still present in https://github.com/fabric8-analytics/fabric8-analytics-tags/blob/1bd605f1f57ea5ea2395d8b1d8a96d009b9a4cb7/pypi_tags.yaml#L11508

**Comment by SaketJNU** [comment]
Hi, The file has few keywords as in the following format:
[1] ? 'cert

  ca'
: {occurrence_count: 1}

[2] ? 'collectd

  transmission

  statistics'
: {occurrence_count: 1}

I think it not a correct one. otherwise, rests are looking fine.
Thanks

**Comment by fridex** [comment]
> Hi, The file has few keywords as in the following format:

These should be filtered out - low occurrence count so the aggregate command should remove them. Isn't it in the original file without changes?

**Comment by SaketJNU** [comment]
ok, then merging it.

**Pull request merged**
